name: Get & save NFT trend data hourly

on:
  schedule:
    - cron: '37 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Create local changes
        run: node index.js
      - name: Commit & Push changes
        uses: actions-js/push@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
